name: Clean Pipeline Workflow

on:
  workflow_dispatch:

jobs:
  clean-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Clean datasets generated in zones
      run: |
        rm -rf datasets/landing-zone/persistent/*
        rm -rf datasets/formatted-zone/*
        rm -rf datasets/trusted-zone/*
        rm -rf datasets/exploitation-zone/*

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "pipeline cleaning"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
